### ISSUE TITLE
Sudden ERROR: server problem (500)

### ISSUE THREAD

**Issue by tucker19** [ku-fpg/hermit-web#7]
I am trying to record the Dictionaries.hs example and in different spots I get 
Status: 500 Internal Server Error. /command

I restart the server and it pops up in a different location. Running on Mac OSX Mavericks

**Comment by xich** [comment]
Does it give any more text for the error message?

**Comment by tucker19** [comment]
No. It only says the Status: 500 Internal Server Error. /command

**Comment by RyanGlScott** [comment]
What commands specifically are giving you a 500 error? I just tried running Dictionaries.hs as well, and it appears to be functional on my end. I'm using the latest version of HERMIT-Web (which requires scotty >= 0.7.0, so you'll have to use the [Github repo](https://github.com/scotty-web/scotty) until it's on Hackage).

**Comment by tucker19** [comment]
ok, I will try with the new Scotty

**Comment by tucker19** [comment]
So I did not update Scotty but I did find this is caused by network connectivity. I moved closer to my router and I have not ran into this since. This just means we will have to always have a good connection for wifi

**Comment by xich** [comment]
Weird... a 500 error would indicate a complete roundtrip of data, so my only guess is that the request data is somehow getting truncated or otherwise corrupted. If that were the case, it would be below the level of any code we've written (in the warp webserver, or the network stack).

I'm going to close this for now, but reopen if it continues to be a problem.
